### ISSUE TITLE
doc/additions Add description for `originatingContractHeight `

### ISSUE THREAD

**Issue by hierophantos** [okTurtles/shelterprotocol.net#5]
`originatingContractHeight` record field to SPMessage `head` docs needs description. Replace `[...]` with copy describing the intent of this field.

https://github.com/okTurtles/shelterprotocol.net/compare/master...doc/additions

**Comment by taoeffect** [comment]
@corrideat I'm guessing this field is an anti-replay measure? Could you comment a bit on it?

**Comment by corrideat** [comment]
I don't think this value is used any longer, and it is a left over from when OP_KEY_SHARE worked differently. That information is now encrypted and not present on the HEAD (the same goes for `originatingContractID`).

**Comment by taoeffect** [comment]
@corrideat Then it sounds like it should be removed from the code, right? I can open an issue for this.

**Comment by corrideat** [comment]
Sure

**Comment by corrideat** [comment]
Regarding replays, I was looking at the code and it seems like it's not really handled (how much of an issue this is, I'm not sure; it only results, at worst, in useless messages).

If this is to be handled, there are at least two changes to make:

1. Tie all OP_KEY_REQUEST signed payload data (i.e., data separately signed inside the payload) to the contract it's being sent to. Right now, it seems to be tied only to the originatingContractID, and add logic to verify this. This prevents re-using an OP_KEY_REQUEST in a different contract.
2. Remember past key requests in the state (this is currently purged) to prevent re-using the same OP_KEY_REQUEST within the same contract.

**Comment by corrideat** [comment]
And answering the original question: even though this is no longer part of the head, it's still used and part of the payload. Its _raison d'être_ is providing an anchor to know which keys were valid at a certain point in time (mostly, for signature validation). So, if a message has originatingContractHeight set to `5`, it means that it must use a signing key that is (was) valid at that particular height.

**Comment by taoeffect** [comment]
Issue created and assigned to you @corrideat: https://github.com/okTurtles/group-income/issues/2329

Regarding replays, if you're certain that they do nothing, then it sounds like nothing needs to be done. If there's no problem, no solution is necessary. ("if it ain't broke, don't fix it")

**Comment by corrideat** [comment]
The 'problem' is message spam and perhaps other things that could be creatively used as part of an attack. But right now, I don't see replays being a significant issue (besides potentially unwanted messages) since `OP_KEY_REQUEST`, by itself, doesn't do anything.

**Comment by taoeffect** [comment]
OK, I've created an issue here so we don't forget about this question and perhaps revisit it at a later date: https://github.com/okTurtles/group-income/issues/2330

**Comment by hierophantos** [comment]
Thanks for clarifying, @taoeffect  and @corrideat!
